### PR TITLE
Adding ical-output support

### PR DESCRIPTION
**Pull request by migmedia**
Feature: `generator` emits calendar-elements: tested with o365 and sabre.
Builder-macro for IcalEvent, IcalCalendar and VcardContact.

### CODE REVIEW

**Comment by dcormier** [comment]
It would be nice to see support for writing ical.

**Comment by Peltoche** [comment]
Hi @migmedia :wave: 

Thanks a lot for this PR, this is some great stuff! I finish to take a look and if everything is ok (it should be) I should merge today.

**Comment by Peltoche** [comment]
If you have the time, there is a linter error for a useless casting but this is not blocking.

**Review by Peltoche — APPROVED** [review]
LGTM

**Comment by Peltoche** [comment]
Damn! December 2021!! :scream: . I'm kind of late! Sorry for the delay...

**Pull request merged**
